# Generated by Django 5.2.3 on 2025-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=128)),
                ("confirm_password", models.CharField(max_length=128)),
            ],
        ),
    ]
