# Generated by Django 5.2.3 on 2025-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="register",
            options={"verbose_name_plural": "Registration"},
        ),
        migrations.AlterField(
            model_name="register",
            name="confirm_password",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=8),
        ),
    ]
